---
# VLAN Provisioning Role - Metadata

galaxy_info:
  author: Network Admin
  description: Role for provisioning VLANs on network switches
  company: Lab Environment
  license: MIT
  min_ansible_version: 2.14
  platforms:
    - name: Cisco IOS
      versions:
        - all
  galaxy_tags:
    - networking
    - cisco
    - vlan
    - switching

dependencies: []
